apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  interval: 5m0s
  chart:
    spec:
      chart: external-secrets
      version: 0.9.9
      sourceRef:
        name: external-secrets
        namespace: flux-system
        kind: HelmRepository
      interval: 5m
  values:
    installCRDs: false
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 25s
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: ${external_secrets_sa_email}
      name: external-secrets-operator
