---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane-charts
  namespace: crossplane-system
spec:
  interval: 5m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: 1.15.0-rc.0.9.ged19cd5d
      sourceRef:
        kind: HelmRepository
        name: crossplane-charts
        namespace: crossplane-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
