---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  url: https://stefanprodan.github.io/descheduler
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: kube-system
      interval: 1m
  values:
    schedule: "*/5 3 * * *"
    deschedulerPolicy:
      LowNodeUtilization:
        enabled: false
      RemovePodsHavingTooManyRestarts:
        enabled: false
      RemovePodsViolatingNodeTaints:
        enabled: false
      RemovePodsViolatingNodeAffinity:
        enabled: false
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: false
      RemovePodsViolatingTopologySpreadConstraint:
        enabled: false
      HighNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              "cpu": 50
              "memory": 50
              "pods": 20
