apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.5.1"
  test:
    enable: false
  values:
    ui:
      color: "#34577c"
      message: "staging"